/* LUNA - duidingen in het Nederlands.
   De berekeningen in astro.js zijn astronomie. De teksten hieronder zijn
   traditionele astrologie: symbooltaal, geen wetenschap. */
(function (global) {
  'use strict';

  var TEKENS = [
    { naam: 'Ram', symbool: '♈\uFE0E', element: 'vuur', kwaliteit: 'hoofd', heerser: 'mars',
      datums: '21 mrt - 19 apr',
      kern: 'Beginnen zonder eerst te vragen of het mag.',
      kernwoorden: ['moed', 'directheid', 'initiatief', 'ongeduld'],
      stijl: 'direct, ongeduldig en zonder omwegen',
      licht: ['Durft als eerste te bewegen', 'Eerlijk tot op het bot', 'Herstelt snel van tegenslag'],
      schaduw: ['Start meer dan af', 'Wrijving zoeken uit verveling'] },
    { naam: 'Stier', symbool: '♉\uFE0E', element: 'aarde', kwaliteit: 'vast', heerser: 'venus',
      datums: '20 apr - 20 mei',
      kern: 'Rust bouwen die niet omvalt als het waait.',
      kernwoorden: ['bestendigheid', 'genot', 'geduld', 'koppigheid'],
      stijl: 'rustig, zintuiglijk en niet op te jagen',
      licht: ['Blijft staan als anderen wankelen', 'Maakt dingen af', 'Weet wat werkelijk fijn is'],
      schaduw: ['Verandering voelt als bedreiging', 'Vasthouden lang nadat het op is'] },
    { naam: 'Tweelingen', symbool: '♊\uFE0E', element: 'lucht', kwaliteit: 'beweeglijk', heerser: 'mercurius',
      datums: '21 mei - 20 jun',
      kern: 'Alles wil weten, aan niets vastzitten.',
      kernwoorden: ['nieuwsgierigheid', 'taal', 'beweeglijkheid', 'onrust'],
      stijl: 'nieuwsgierig, wendbaar en woordrijk',
      licht: ['Legt verband tussen alles', 'Praat zich overal in', 'Verveelt anderen nooit'],
      schaduw: ['Blijft aan de oppervlakte', 'Twee meningen tegelijk'] },
    { naam: 'Kreeft', symbool: '♋\uFE0E', element: 'water', kwaliteit: 'hoofd', heerser: 'maan',
      datums: '21 jun - 22 jul',
      kern: 'Een plek maken waar het veilig is.',
      kernwoorden: ['zorg', 'geheugen', 'bescherming', 'gevoeligheid'],
      stijl: 'zorgzaam, beschermend en met een lang geheugen',
      licht: ['Voelt aan wat iemand nodig heeft', 'Trouw door dik en dun', 'Maakt van elke ruimte een thuis'],
      schaduw: ['Terugtrekken in het schild', 'Oud zeer blijft meereizen'] },
    { naam: 'Leeuw', symbool: '♌\uFE0E', element: 'vuur', kwaliteit: 'vast', heerser: 'zon',
      datums: '23 jul - 22 aug',
      kern: 'Durven stralen zonder je te verontschuldigen.',
      kernwoorden: ['warmte', 'trots', 'creativiteit', 'erkenning'],
      stijl: 'royaal, warm en zichtbaar',
      licht: ['Geeft anderen moed', 'Groothartig zonder rekenen', 'Maakt van gewoon iets feestelijks'],
      schaduw: ['Erkenning nodig om te bestaan', 'Trots die niet buigt'] },
    { naam: 'Maagd', symbool: '♍\uFE0E', element: 'aarde', kwaliteit: 'beweeglijk', heerser: 'mercurius',
      datums: '23 aug - 22 sep',
      kern: 'Beter maken wat al bestaat.',
      kernwoorden: ['precisie', 'dienstbaarheid', 'analyse', 'zelfkritiek'],
      stijl: 'zorgvuldig, opmerkzaam en praktisch',
      licht: ['Ziet wat anderen missen', 'Helpt zonder ophef', 'Maakt chaos werkbaar'],
      schaduw: ['Nooit goed genoeg', 'Zorg verkleed als kritiek'] },
    { naam: 'Weegschaal', symbool: '♎\uFE0E', element: 'lucht', kwaliteit: 'hoofd', heerser: 'venus',
      datums: '23 sep - 22 okt',
      kern: 'Zoeken naar de vorm waarin niemand verliest.',
      kernwoorden: ['evenwicht', 'schoonheid', 'diplomatie', 'twijfel'],
      stijl: 'afwegend, charmant en op harmonie gericht',
      licht: ['Ziet altijd de andere kant', 'Maakt het mooier om zich heen', 'Verzacht conflict'],
      schaduw: ['Kiezen stelt het eindeloos uit', 'Vrede boven waarheid'] },
    { naam: 'Schorpioen', symbool: '♏\uFE0E', element: 'water', kwaliteit: 'vast', heerser: 'pluto',
      datums: '23 okt - 21 nov',
      kern: 'Niets half doen, ook het voelen niet.',
      kernwoorden: ['diepte', 'intensiteit', 'loyaliteit', 'controle'],
      stijl: 'intens, alles of niets',
      licht: ['Houdt stand in wat anderen mijden', 'Loyaal tot het uiterste', 'Ziet dwars door gedoe heen'],
      schaduw: ['Controle als bescherming', 'Wantrouwen dat niet meer opgaat'] },
    { naam: 'Boogschutter', symbool: '♐\uFE0E', element: 'vuur', kwaliteit: 'beweeglijk', heerser: 'jupiter',
      datums: '22 nov - 21 dec',
      kern: 'De horizon blijft interessanter dan de kamer.',
      kernwoorden: ['vrijheid', 'betekenis', 'optimisme', 'rusteloosheid'],
      stijl: 'ruimhartig, avontuurlijk en eerlijk tot het botte af',
      licht: ['Ziet altijd een uitweg', 'Aanstekelijk vertrouwen', 'Zegt wat waar is'],
      schaduw: ['Weg is makkelijker dan blijven', 'Beloftes groter dan de agenda'] },
    { naam: 'Steenbok', symbool: '♑\uFE0E', element: 'aarde', kwaliteit: 'hoofd', heerser: 'saturnus',
      datums: '22 dec - 19 jan',
      kern: 'Bouwen aan iets dat je overleeft.',
      kernwoorden: ['discipline', 'verantwoordelijkheid', 'geduld', 'strengheid'],
      stijl: 'beheerst, doelgericht en met de lange termijn in beeld',
      licht: ['Houdt vol als niemand kijkt', 'Draagt wat gedragen moet worden', 'Maakt plannen die kloppen'],
      schaduw: ['Alles alleen willen dragen', 'Streng voor zichzelf, dus ook voor jou'] },
    { naam: 'Waterman', symbool: '♒\uFE0E', element: 'lucht', kwaliteit: 'vast', heerser: 'uranus',
      datums: '20 jan - 18 feb',
      kern: 'Het kan ook anders, en dat is het punt.',
      kernwoorden: ['eigenzinnigheid', 'overzicht', 'vernieuwing', 'afstand'],
      stijl: 'eigenzinnig, helder en een stap opzij van de massa',
      licht: ['Ziet het patroon boven de ruzie', 'Trouw aan het principe', 'Geeft anderen ruimte'],
      schaduw: ['Koelte als het te dichtbij komt', 'Gelijk hebben boven contact'] },
    { naam: 'Vissen', symbool: '♓\uFE0E', element: 'water', kwaliteit: 'beweeglijk', heerser: 'neptunus',
      datums: '19 feb - 20 mrt',
      kern: 'De grens tussen jou en de rest is dun.',
      kernwoorden: ['inleving', 'verbeelding', 'overgave', 'ontvluchting'],
      stijl: 'dromerig, meelevend en zonder harde randen',
      licht: ['Voelt de kamer aan voordat er iets gezegd is', 'Vergeeft echt', 'Verbeelding zonder rem'],
      schaduw: ['Neemt andermans stemming over', 'Vluchten als het te hard wordt'] }
  ];

  var ELEMENTEN = {
    vuur:  { naam: 'Vuur',  kleur: '#ffb27a', kern: 'beweging, moed, aanzetten' },
    aarde: { naam: 'Aarde', kleur: '#b7cf9a', kern: 'houvast, vorm, volhouden' },
    lucht: { naam: 'Lucht', kleur: '#a8d3f0', kern: 'denken, taal, overzicht' },
    water: { naam: 'Water', kleur: '#c4abff', kern: 'gevoel, geheugen, verbinding' }
  };

  var KWALITEITEN = {
    hoofd:      'begint iets',
    vast:       'houdt iets vast',
    beweeglijk: 'past iets aan'
  };

  var PLANETEN = {
    zon:       { naam: 'Zon', symbool: '☉', kleur: 'primary',
                 thema: 'kernidentiteit', domein: 'wie je bent als niemand meekijkt',
                 vraag: 'Waar kom ik tot leven?',
                 werkwoord: 'straalt' },
    maan:      { naam: 'Maan', symbool: '☽', kleur: 'secondary',
                 thema: 'emotionele wereld', domein: 'wat je nodig hebt om je veilig te voelen',
                 vraag: 'Wat kalmeert mij werkelijk?',
                 werkwoord: 'voelt' },
    mercurius: { naam: 'Mercurius', symbool: '☿', kleur: 'tertiary',
                 thema: 'denken en spreken', domein: 'hoe je opneemt, ordent en doorgeeft',
                 vraag: 'Hoe begrijp ik de wereld?',
                 werkwoord: 'denkt' },
    venus:     { naam: 'Venus', symbool: '♀', kleur: 'rose',
                 thema: 'liefde en waarden', domein: 'wat je mooi vindt en hoe je hecht',
                 vraag: 'Wat is mij dierbaar?',
                 werkwoord: 'hecht' },
    mars:      { naam: 'Mars', symbool: '♂', kleur: 'ember',
                 thema: 'actie en drive', domein: 'hoe je wilt, doorzet en ruzie maakt',
                 vraag: 'Waar zet ik mijn kracht op in?',
                 werkwoord: 'handelt' },
    jupiter:   { naam: 'Jupiter', symbool: '♃', kleur: 'primary',
                 thema: 'groei en vertrouwen', domein: 'waar je ruimte krijgt en te ver gaat',
                 vraag: 'Waarin geloof ik?',
                 werkwoord: 'groeit' },
    saturnus:  { naam: 'Saturnus', symbool: '♄', kleur: 'outline',
                 thema: 'structuur en grenzen', domein: 'wat je moet leren dragen',
                 vraag: 'Wat vraagt tijd en discipline?',
                 werkwoord: 'begrenst' },
    uranus:    { naam: 'Uranus', symbool: '♅', kleur: 'tertiary',
                 thema: 'breuk en vernieuwing', domein: 'waar je afwijkt en wakker geschud wordt',
                 vraag: 'Waar wil ik vrij zijn?',
                 werkwoord: 'breekt open' },
    neptunus:  { naam: 'Neptunus', symbool: '♆', kleur: 'secondary',
                 thema: 'verbeelding en versluiering', domein: 'waar grenzen vervagen',
                 vraag: 'Waar verlang ik naar voorbij het gewone?',
                 werkwoord: 'verzacht' },
    pluto:     { naam: 'Pluto', symbool: '♇', kleur: 'plum',
                 thema: 'macht en transformatie', domein: 'wat afsterft zodat iets anders kan beginnen',
                 vraag: 'Wat moet ik loslaten om te groeien?',
                 werkwoord: 'transformeert' },
    knoop:     { naam: 'Maansknoop', symbool: '☊', kleur: 'outline',
                 thema: 'ontwikkelrichting', domein: 'de kant waarin je groeit',
                 vraag: 'Waarheen beweegt mijn leven?',
                 werkwoord: 'wijst' },
    asc:       { naam: 'Ascendant', symbool: 'AC', kleur: 'tertiary',
                 thema: 'hoe anderen jou zien', domein: 'de deur waardoor je binnenkomt',
                 vraag: 'Welke indruk maak ik voordat ik iets zeg?',
                 werkwoord: 'toont' },
    mc:        { naam: 'Midhemel', symbool: 'MC', kleur: 'primary',
                 thema: 'richting en roeping', domein: 'waar je zichtbaar wordt in de wereld',
                 vraag: 'Waar wil ik voor staan?',
                 werkwoord: 'richt' }
  };

  var HUIZEN = [
    { naam: '1e huis', thema: 'Jij en je verschijning',
      tekst: 'Hoe je binnenkomt, hoe je eruitziet, hoe je begint. Het huis van de eerste indruk.' },
    { naam: '2e huis', thema: 'Bezit en eigenwaarde',
      tekst: 'Wat je bezit en wat je waard vindt. Geld, spullen, talenten, en of je vindt dat je ze mag hebben.' },
    { naam: '3e huis', thema: 'Denken en directe omgeving',
      tekst: 'Gesprekken, broers en zussen, korte reizen, leren. De wereld op loopafstand.' },
    { naam: '4e huis', thema: 'Thuis en afkomst',
      tekst: 'Familie, wortels, het huis waarin je opgroeide en het huis dat je zelf maakt.' },
    { naam: '5e huis', thema: 'Spel en creatie',
      tekst: 'Verliefdheid, kinderen, kunst, alles wat je maakt omdat het leuk is.' },
    { naam: '6e huis', thema: 'Werk en gezondheid',
      tekst: 'De dagelijkse routine, je lichaam, je vak, en de zorg die je aan anderen besteedt.' },
    { naam: '7e huis', thema: 'De ander',
      tekst: 'Partnerschap, samenwerking, ook openlijke tegenstanders. Wie je tegenover je vindt.' },
    { naam: '8e huis', thema: 'Wat gedeeld wordt',
      tekst: 'Intimiteit, gedeeld geld, verlies en transformatie. Alles wat je niet alleen doet.' },
    { naam: '9e huis', thema: 'Verte en betekenis',
      tekst: 'Reizen, studie, geloof, alles wat je blik verruimt.' },
    { naam: '10e huis', thema: 'Positie in de wereld',
      tekst: 'Je vak, je reputatie, waar je voor staat als mensen je naam noemen.' },
    { naam: '11e huis', thema: 'Kring en toekomst',
      tekst: 'Vrienden, groepen, idealen, de toekomst waar je aan meebouwt.' },
    { naam: '12e huis', thema: 'Wat achter je ligt',
      tekst: 'Het onbewuste, afzondering, dat wat je aan jezelf niet ziet. Rust en ruis tegelijk.' }
  ];

  var ASPECTEN = {
    conjunctie: { naam: 'conjunctie', teken: '☌\uFE0E', aard: 'neutraal',
      kort: 'versmelt', kleur: '#ffe08e',
      tekst: 'Twee krachten staan op dezelfde plek en zijn niet meer los te trekken. Wat de een doet, kleurt de ander onmiddellijk.' },
    sextiel: { naam: 'sextiel', teken: '⚹\uFE0E', aard: 'harmonisch',
      kort: 'biedt aan', kleur: '#b7cf9a',
      tekst: 'Een open deur. Er is een kans, maar je moet er zelf doorheen stappen; vanzelf gebeurt er niets.' },
    vierkant: { naam: 'vierkant', teken: '□\uFE0E', aard: 'spanning',
      kort: 'schuurt met', kleur: '#ffb4ab',
      tekst: 'Twee krachten willen tegelijk iets anders. Het wringt, en juist die wrijving zet in beweging.' },
    driehoek: { naam: 'driehoek', teken: '△\uFE0E', aard: 'harmonisch',
      kort: 'stroomt met', kleur: '#a8d3f0',
      tekst: 'Alles gaat hier makkelijk, zo makkelijk dat je het talent zelf nauwelijks opmerkt.' },
    oppositie: { naam: 'oppositie', teken: '☍\uFE0E', aard: 'spanning',
      kort: 'staat tegenover', kleur: '#d0bcff',
      tekst: 'Twee kanten staan recht tegenover elkaar. Je slingert ertussen tot je ontdekt dat ze elkaar nodig hebben.' }
  };

  var MAANFASEN = [
    { naam: 'Nieuwe Maan', kern: 'Beginnen in het donker.',
      tekst: 'De maan is onzichtbaar en dat is precies de bedoeling. Zet iets in gang zonder het al te laten zien. Wat je nu zaait, hoeft nog niets op te leveren.',
      goedVoor: ['Intenties zetten', 'Iets stils beginnen', 'Opruimen', 'Alleen zijn'] },
    { naam: 'Wassende Sikkel', kern: 'De eerste stap na het besluit.',
      tekst: 'Het eerste randje licht. Je plan bestaat, maar is nog kwetsbaar. Vertel het aan een of twee mensen, niet aan iedereen.',
      goedVoor: ['Eerste stap zetten', 'Klein testen', 'Steun zoeken', 'Doorzetten'] },
    { naam: 'Eerste Kwartier', kern: 'De eerste tegenwind.',
      tekst: 'Halverwege naar vol. Hier komt het verzet: te weinig tijd, twijfel, iemand die het anders wil. Beslissen is nu belangrijker dan gelijk hebben.',
      goedVoor: ['Knopen doorhakken', 'Bijsturen', 'Grenzen stellen', 'Volhouden'] },
    { naam: 'Wassende Maan', kern: 'Bijschaven en doorzetten.',
      tekst: 'De energie bouwt zich op. Verfijn je plannen en zet concrete stappen. Dit is een tijd van groei, van afmaken wat je begonnen bent.',
      goedVoor: ['Projecten afronden', 'Reflecteren', 'Creatief werk', 'Gesprekken'] },
    { naam: 'Volle Maan', kern: 'Alles staat in het licht.',
      tekst: 'Maximale verlichting, ook van wat je liever niet zag. Gevoelens lopen hoog op en dingen komen tot een hoogtepunt of tot een einde.',
      goedVoor: ['Vieren', 'Uitspreken', 'Afsluiten', 'Loslaten'] },
    { naam: 'Afnemende Maan', kern: 'Delen wat je hebt geleerd.',
      tekst: 'Het licht neemt af. De oogst is binnen; nu is het moment om door te geven, te bedanken en de rekening op te maken.',
      goedVoor: ['Doorgeven', 'Bedanken', 'Evalueren', 'Verzorgen'] },
    { naam: 'Laatste Kwartier', kern: 'Weggooien wat af is.',
      tekst: 'Tijd om te schrappen. Wat de afgelopen cyclus niet gebracht heeft, hoeft niet mee naar de volgende.',
      goedVoor: ['Opruimen', 'Vergeven', 'Afscheid nemen', 'Vereenvoudigen'] },
    { naam: 'Afnemende Sikkel', kern: 'Rust voor het opnieuw begint.',
      tekst: 'Het laatste randje licht voor het donker. Weinig energie, veel inzicht. Doe niets groots; slaap, droom, wacht.',
      goedVoor: ['Rusten', 'Dromen', 'Stilte', 'Terugkijken'] }
  ];

  var RETROGRADE = {
    mercurius: 'Mercurius loopt schijnbaar terug. Gesprekken lopen anders dan bedoeld, techniek hapert, afspraken schuiven. Het is een periode voor herzien, herlezen en opnieuw contact opnemen, niet voor grote nieuwe afspraken.',
    venus: 'Venus loopt terug. Oude liefdes en oude vragen over waarde komen langs. Een slecht moment voor onomkeerbare keuzes in liefde of grote aankopen, een goed moment om te ontdekken wat je werkelijk waardeert.',
    mars: 'Mars loopt terug. Je drive lijkt weg of slaat naar binnen. Kwaadheid stapelt zich eerder op dan dat ze eruit komt. Sleutel je plan bij in plaats van door te duwen.',
    jupiter: 'Jupiter loopt terug. Groei verplaatst zich naar binnen: minder uitbreiden, meer begrijpen waarom je iets eigenlijk wilde.',
    saturnus: 'Saturnus loopt terug. Structuren worden getoetst. Wat op een wankele basis staat, laat dat nu zien, zodat je het kunt verstevigen.',
    uranus: 'Uranus loopt terug. De onrust gaat naar binnen. De breuk die je in de wereld wilde forceren, blijkt eerst in jezelf te moeten gebeuren.',
    neptunus: 'Neptunus loopt terug. Mist trekt langzaam op. Je ziet scherper wat illusie was, ook als dat niet fijn is.',
    pluto: 'Pluto loopt terug. Verandering werkt onder de oppervlakte door. Wat naar boven komt, is meestal iets wat je al langer wist.'
  };

  var ADVIEZEN = [
    'Kies nieuwsgierigheid boven controle.',
    'Doe vandaag de kleinste versie van het grote plan.',
    'Wat je nu niet zegt, zeg je later duurder.',
    'Rust is ook een besluit.',
    'Laat het onaf zijn tot morgen.',
    'Vraag door waar je normaal knikt.',
    'Bescherm je aandacht als was het geld.',
    'Het hoeft niet af, het moet eerlijk.',
    'Wacht een dag met je antwoord.',
    'Doe het langzaam en daarom goed.',
    'Zeg ja tegen minder, meen het meer.',
    'Wat schuurt, wijst een richting aan.',
    'Neem de omweg, daar zit het inzicht.',
    'Begin voordat je klaar bent.',
    'Laat iemand je helpen.',
    'Wat je vandaag opruimt, draag je morgen niet.',
    'Vertrouw op wat anders aanvoelt.',
    'Niet elk gevoel vraagt om actie.',
    'Doe het onbeholpen, maar doe het.',
    'Bewaar je scherpte voor wat het waard is.',
    'Twijfel is informatie, geen fout.',
    'Stel de vraag die je vermijdt.',
    'Kies de versie die je over een jaar nog kunt uitleggen.',
    'Zwijgen mag ook een antwoord zijn.',
    'Ga naar buiten voordat je beslist.',
    'Doe eerst het saaie deel.',
    'Wat je aandacht geeft, groeit; kies dus goed.',
    'Neem jezelf minder persoonlijk.',
    'Er is meer tijd dan je denkt, maar minder dan je hoopt.',
    'Laat vandaag iets ongezegd wat toch niet hielp.'
  ];

  global.LunaContent = {
    TEKENS: TEKENS, ELEMENTEN: ELEMENTEN, KWALITEITEN: KWALITEITEN,
    PLANETEN: PLANETEN, HUIZEN: HUIZEN, ASPECTEN: ASPECTEN,
    MAANFASEN: MAANFASEN, RETROGRADE: RETROGRADE, ADVIEZEN: ADVIEZEN
  };
})(typeof window !== 'undefined' ? window : globalThis);
